This theme is based on Adwaita from gtk4 and customized for Inkscape.
(https://gitlab.gnome.org/GNOME/gtk/-/tree/main/gtk/theme)

SASS compiler needed to build the theme:
https://github.com/sass/dart-sass/releases/

To build the theme:
./build.sh
