// SPDX-License-Identifier: GPL-2.0-or-later
/** @file
 * TODO: insert short description here
 *//*
 * Authors: see git history
 *
 * Copyright (C) 2018 Authors
 * Released under GNU GPL v2+, read the file 'COPYING' for more information.
 */
#ifndef SEEN_SP_DOCUMENT_UNDO_H
#define SEEN_SP_DOCUMENT_UNDO_H

#include "util-string/context-string.h" // ContextString
#include <glib.h>   // gboolean, gchar
#include <optional>
#include <functional>
#include <memory>
#include <utility>
#include <sigc++/signal.h>

namespace Glib {
    class ustring;
}

#include <functional>

class SPDocument;

namespace Inkscape {

struct UndoInteractionState;
struct UndoInteractionLifetime;

namespace XML {
class Event;
}

class DocumentUndo
{
public:

    /**
     * A document-local rollback point for a live UI interaction.
     *
     * It isolates XML generated by the interaction from any pre-existing
     * partial undo log. Destroying an active token rolls the interaction back;
     * committing it creates the normal single undo entry.
     */
    class RollbackableInteraction {
    public:
        RollbackableInteraction(RollbackableInteraction const &) = delete;
        RollbackableInteraction &operator=(RollbackableInteraction const &) = delete;
        RollbackableInteraction(RollbackableInteraction &&other) noexcept;
        RollbackableInteraction &operator=(RollbackableInteraction &&other) noexcept;
        ~RollbackableInteraction();

        bool active() const;
        // Read-only ownership check: true only while this is the current, active,
        // non-interrupted token for the supplied live document at a writable
        // synchronous boundary. It never creates lifetime/state, mutates history,
        // acquires a lease or emits callbacks. A live caller still keeps its
        // synchronous holdInteractionOperation and private owner alive; an atomic
        // token already holds its admitted settlement lease. The argument may be
        // dangling: it is only compared against the token's native lifetime
        // document identity before any dereference.
        bool validFor(SPDocument const *document) const;
        // Current, live atomic owner only; read-only, with no history callbacks.
        bool validAtomicFor(SPDocument const *document) const;
        bool interrupted() const;
        // Atomic mode only: run native pre-commit work, revalidate, then publish.
        // False means no history publication; an active token still needs
        // rollback, while a no-log result is already settled and inactive.
        // Settled tokens retain neither the history fence nor an owner lease.
        bool commitAtomically(Util::Internal::ContextString description,
                              Glib::ustring const &icon, std::function<bool()> ready);
        // Normal live mode keeps pre-commit retirement. Atomic mode notifies
        // only after history publication and the next XML transaction starts;
        // callback writes/done() then belong to subsequent work, never this
        // commit. The document operation lease survives all retirement callbacks,
        // even if they destroy the token; it is released on return from settlement.
        // An atomic no-log result has no publication and emits no retirement.
        sigc::connection connectRetired(sigc::slot<void()> slot);
        void commit(Util::Internal::ContextString event_description,
                    Glib::ustring const &undo_icon,
                    unsigned int object_modified_tag = 0);
        void rollback() noexcept;

    private:
        friend class DocumentUndo;
        explicit RollbackableInteraction(std::shared_ptr<UndoInteractionState> state)
            : _state(std::move(state))
        {}

        std::shared_ptr<UndoInteractionState> _state;
    };

    static std::optional<RollbackableInteraction> beginRollbackableInteraction(SPDocument *document);
    static bool interactionActive(SPDocument const *document);
    // Opt-in synchronous boundary: refuses pending unrelated XML/history work,
    // blocks nested history operations, and owns settlement through deferred close.
    static std::optional<RollbackableInteraction> beginAtomicInteraction(SPDocument *document);
    // Command admission requires the sole active operation to be this caller's
    // lease from holdInteractionOperation; copies/aliases retain owner identity.
    static std::optional<RollbackableInteraction> beginAtomicCommandInteraction(
        SPDocument *document, std::shared_ptr<void> const &owner_lease);
    // Caller-local thread seam; production leaves it null. Only the atomic path
    // consults it, before real allocation / inside post-commit notification.
    enum class AtomicSettlementStage { EventConstruction, HistoryInsertion, EventLogNotification };
    using AtomicSettlementFault = bool (*)(AtomicSettlementStage);
    static void setAtomicSettlementFaultForTesting(AtomicSettlementFault) noexcept;


    // Deferred work belongs to the document, never to an idle holding a view.
    static bool interactionIsQuiescent(SPDocument *document);
    static void deferInteractionCleanup(SPDocument *document, std::function<void(SPDocument &)> cleanup,
                                        bool immediate_if_quiescent = false);
    static std::shared_ptr<void> holdInteractionOperation(SPDocument *document);
    static std::shared_ptr<void> holdPublication(SPDocument *document);
    static bool publicationCompletable(SPDocument const *document) noexcept;
    static bool publicationPending(SPDocument const *document) noexcept;
    // Atomic mutation through notification/retirement and publisher teardown.
    // Excludes ordinary previews, operation leases and detached file-worker output.
    static bool publicationInProgress(SPDocument const *document) noexcept;
    static void markInteractionBaselineDirty(SPDocument *document);
    static bool whenPublicationCompletable(SPDocument *document,
                                           std::function<void(SPDocument &)> continuation,
                                           std::function<void(SPDocument &)> report_only,
                                           std::function<bool()> finished = {});
    // Drain only at a safe publication boundary (including an accepted close).
    static void flushPublicationCompletions(SPDocument *document);
    static void rollbackLiveInteractionForClose(SPDocument *document);
    static void clearStaleInteractionForClose(SPDocument *document) noexcept;
    static bool interactionCloseRequested(SPDocument *document);

    // Narrow read-only readiness probes for the F6a Packet A synchronous
    // file-operation component. They never create or mutate interaction
    // lifetime state, expose no operation depth, and do not change the meaning
    // of interactionIsQuiescent/deferUntilInteractionQuiescent.
    // Fresh admission: no operation lease is held yet.
    static bool fileOperationFreshReady(SPDocument const *document) noexcept;
    // Before each output attempt while the caller holds exactly its own single
    // operation lease. A newly pending close request may wait; a hard-closing
    // document is not ready.
    static bool fileOperationOutputReady(SPDocument const *document) noexcept;
    // Registered owners retain their unique_ptr until this continuation runs.
    // Private owners must themselves survive every synchronous operation.
    static bool deferUntilInteractionQuiescent(SPDocument *document,
                                              std::function<void(SPDocument &)> continuation,
                                              bool closing = false, bool no_defer = false);
    static void documentClosing(SPDocument *document) noexcept;

    /**
     * Set undo sensitivity.
     *
     * Don't use this to temporarily turn sensitivity off, use ScopedInsensitive instead.
    */
    static void setUndoSensitive(SPDocument *doc, bool sensitive);

    static bool getUndoSensitive(SPDocument const *document);

    static void clearUndo(SPDocument *document);

    static void clearRedo(SPDocument *document);

    /* undo_icon is only used in History dialog. */
    static void done(SPDocument *document, Util::Internal::ContextString event_description, Glib::ustring const &undo_icon, unsigned int object_modified_tag = 0);

    static void maybeDone(SPDocument *document, const gchar *keyconst, Util::Internal::ContextString event_description, Glib::ustring const &undo_icon, unsigned int object_modified_tag = 0);

private:
    friend class ::SPDocument;
    // Native display update must record its XML while the atomic fence owns the
    // transaction. This query grants no history/sensitivity bypass to callbacks.
    static bool atomicHistoryProtected(SPDocument const *document);
    // Read-only shared predicate for native document/state ownership, called by
    // RollbackableInteraction::validFor.
    static std::optional<RollbackableInteraction> beginRollbackableInteraction(
        SPDocument *document, std::shared_ptr<void> const *owner_lease);
    static std::optional<RollbackableInteraction> beginAtomicInteraction(
        SPDocument *document, std::shared_ptr<void> const *owner_lease);
    static bool interactionValidFor(UndoInteractionState const &state, SPDocument const *document);
    static std::shared_ptr<UndoInteractionLifetime> interactionLifetime(SPDocument *document);
    static void sealInteraction(SPDocument *document);
    static bool atomicHistoryConflict(SPDocument *document);
    static bool commitAtomicInteraction(RollbackableInteraction &interaction,
                                       Util::Internal::ContextString description,
                                       Glib::ustring const &icon, std::function<bool()> ready);
    static void commitInteraction(RollbackableInteraction &interaction,
                                  Util::Internal::ContextString event_description,
                                  Glib::ustring const &undo_icon,
                                  unsigned int object_modified_tag);
    static void rollbackInteraction(RollbackableInteraction &interaction) noexcept;

    static void finish_incomplete_transaction(SPDocument &document);

    static void perform_document_update(SPDocument &document);

public:
    static void resetKey(SPDocument *document);

    /**
     * Set the timeout for the last maybeDone call.
     */
    static void setKeyExpires(SPDocument *document, double timeout);

    static void cancel(SPDocument *document);

    /**
     * Fence for an operation that may have to be undone on its own while it runs inside a caller's larger,
     * still-open transaction (skip_undo callers). detachPendingChanges() moves everything not yet committed out of
     * the way and starts a fresh XML transaction; it returns null (no fence) when the document is not sensitive.
     * Afterwards exactly one of reattachPendingChanges() (keep the work: the caller's own pending changes come
     * first, then this operation's) or rollbackToDetachedChanges() (discard only this operation's changes and
     * restore the caller's) must be called with the returned fence.
     */
    struct PendingFence {
        XML::Event *pending = nullptr;
    };
    static std::optional<PendingFence> detachPendingChanges(SPDocument *document);
    static void reattachPendingChanges(SPDocument *document, PendingFence fence);
    static void rollbackToDetachedChanges(SPDocument *document, PendingFence fence) noexcept;

    static gboolean undo(SPDocument *document);

    /**
     * Opaque marker of the current top of the Undo stack (null when empty). Take it before a cancellable
     * interaction (a knot drag, a connector reroute) and pass it to undoSinceMark() when the interaction is
     * cancelled, so that cancelling never undoes an unrelated earlier step. Also drops the pending action key, so
     * a keyed commit by the interaction can never merge into the step that is on top now.
     */
    static void const *undoStackMark(SPDocument *document);

    /**
     * Cancel what happened since @a mark was taken. When a new Undo step was pushed since then, undo it and return
     * true. When none was, undo nothing that predates the interaction: only changes not yet committed are rolled
     * back (cancel()), and false is returned.
     */
    static bool undoSinceMark(SPDocument *document, void const *mark);

    static gboolean redo(SPDocument *document);

    /**
     * RAII-style mechanism for creating a temporary undo-insensitive context.
     *
     * \verbatim
        {
            DocumentUndo::ScopedInsensitive tmp(document);
            ... do stuff ...
            // "tmp" goes out of scope here and automatically restores undo-sensitivity
        } \endverbatim
     */
    class ScopedInsensitive {
        SPDocument * m_doc;
        bool m_saved;
        std::shared_ptr<void> m_operation;

      public:
        ScopedInsensitive(SPDocument *doc)
            : m_doc(doc), m_operation(holdInteractionOperation(doc))
        {
            m_saved = getUndoSensitive(doc);
            setUndoSensitive(doc, false);
        }
        ~ScopedInsensitive() { setUndoSensitive(m_doc, m_saved); }
    };
};

} // namespace Inkscape

#endif // SEEN_SP_DOCUMENT_UNDO_H

/*
  Local Variables:
  mode:c++
  c-file-style:"stroustrup"
  c-file-offsets:((innamespace . 0)(inline-open . 0)(case-label . +))
  indent-tabs-mode:nil
  fill-column:99
  End:
*/
// vim: filetype=cpp:expandtab:shiftwidth=4:tabstop=8:softtabstop=4:fileencoding=utf-8:textwidth=99 :
